Traceback (most recent call last):
  File "/Users/sebouithol/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/sebouithol/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/sebouithol/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/sebouithol/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/sebouithol/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/sebouithol/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/sebouithol/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/sebouithol/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
filename = "Flanker_EEG_52_12052022.bdf"

raw_eeg = mne.io.read_raw_bdf(filename, preload=True)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/var/folders/ym/sgmmtl6j62gdmqhqjzgb95_00000gn/T/ipykernel_57289/83885273.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mfilename[0m [0;34m=[0m [0;34m"Flanker_EEG_52_12052022.bdf"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0mraw_eeg[0m [0;34m=[0m [0mmne[0m[0;34m.[0m[0mio[0m[0;34m.[0m[0mread_raw_bdf[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mpreload[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/opt/anaconda3/lib/python3.9/site-packages/mne/io/edf/edf.py[0m in [0;36mread_raw_bdf[0;34m(input_fname, eog, misc, stim_channel, exclude, infer_types, include, preload, units, encoding, verbose)[0m
[1;32m   1711[0m     [0;32mif[0m [0mext[0m [0;34m!=[0m [0;34m"bdf"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1712[0m         [0;32mraise[0m [0mNotImplementedError[0m[0;34m([0m[0;34mf"Only BDF files are supported, got {ext}."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1713[0;31m     return RawEDF(
[0m[1;32m   1714[0m         [0minput_fname[0m[0;34m=[0m[0minput_fname[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1715[0m         [0meog[0m[0;34m=[0m[0meog[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m<decorator-gen-253>[0m in [0;36m__init__[0;34m(self, input_fname, eog, misc, stim_channel, exclude, infer_types, preload, include, units, encoding, verbose)[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/mne/io/edf/edf.py[0m in [0;36m__init__[0;34m(self, input_fname, eog, misc, stim_channel, exclude, infer_types, preload, include, units, encoding, verbose)[0m
[1;32m    151[0m         [0mlogger[0m[0;34m.[0m[0minfo[0m[0;34m([0m[0;34m"Extracting EDF parameters from {}..."[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0minput_fname[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    152[0m         [0minput_fname[0m [0;34m=[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mabspath[0m[0;34m([0m[0minput_fname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 153[0;31m         info, edf_info, orig_units = _get_info(
[0m[1;32m    154[0m             [0minput_fname[0m[0;34m,[0m [0mstim_channel[0m[0;34m,[0m [0meog[0m[0;34m,[0m [0mmisc[0m[0;34m,[0m [0mexclude[0m[0;34m,[0m [0minfer_types[0m[0;34m,[0m [0mpreload[0m[0;34m,[0m [0minclude[0m[0;34m[0m[0;34m[0m[0m
[1;32m    155[0m         )

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/mne/io/edf/edf.py[0m in [0;36m_get_info[0;34m(fname, stim_channel, eog, misc, exclude, infer_types, preload, include)[0m
[1;32m    487[0m     [0mmisc[0m [0;34m=[0m [0mmisc[0m [0;32mif[0m [0mmisc[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m [0;32melse[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    488[0m [0;34m[0m[0m
[0;32m--> 489[0;31m     [0medf_info[0m[0;34m,[0m [0morig_units[0m [0;34m=[0m [0m_read_header[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0mexclude[0m[0;34m,[0m [0minfer_types[0m[0;34m,[0m [0minclude[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    490[0m [0;34m[0m[0m
[1;32m    491[0m     [0;31m# XXX: `tal_ch_names` to pass to `_check_stim_channel` should be computed[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/mne/io/edf/edf.py[0m in [0;36m_read_header[0;34m(fname, exclude, infer_types, include)[0m
[1;32m    471[0m     [0mlogger[0m[0;34m.[0m[0minfo[0m[0;34m([0m[0;34m"%s file detected"[0m [0;34m%[0m [0mext[0m[0;34m.[0m[0mupper[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    472[0m     [0;32mif[0m [0mext[0m [0;32min[0m [0;34m([0m[0;34m"bdf"[0m[0;34m,[0m [0;34m"edf"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 473[0;31m         [0;32mreturn[0m [0m_read_edf_header[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0mexclude[0m[0;34m,[0m [0minfer_types[0m[0;34m,[0m [0minclude[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    474[0m     [0;32melif[0m [0mext[0m [0;34m==[0m [0;34m"gdf"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    475[0m         [0;32mreturn[0m [0m_read_gdf_header[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0mexclude[0m[0;34m,[0m [0minclude[0m[0;34m)[0m[0;34m,[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/mne/io/edf/edf.py[0m in [0;36m_read_edf_header[0;34m(fname, exclude, infer_types, include)[0m
[1;32m    719[0m     [0medf_info[0m [0;34m=[0m [0;34m{[0m[0;34m"events"[0m[0;34m:[0m [0;34m[[0m[0;34m][0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[1;32m    720[0m [0;34m[0m[0m
[0;32m--> 721[0;31m     [0;32mwith[0m [0mopen[0m[0;34m([0m[0mfname[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m [0;32mas[0m [0mfid[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    722[0m         [0mfid[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;36m8[0m[0;34m)[0m  [0;31m# version (unused here)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    723[0m [0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/Users/sebouithol/DataspellProjects/Experimentation2DataAnalysis/Experimentation2/Flanker_EEG_52_12052022.bdf'
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sebouithol/DataspellProjects/Experimentation2DataAnalysis/Experimentation2/Flanker_EEG_52_12052022.bdf'

